AWSTemplateFormatVersion: '2010-09-09'
Description: 'Qualys Lambda Scanner - Single Account (Native Lambda, No Docker)'

Parameters:
  QualysPod:
    Type: String
    Description: 'Qualys POD (e.g., US1, US2, EU1)'
    Default: 'US2'
    AllowedValues:
      - US1
      - US2
      - US3
      - US4
      - GOV1
      - EU1
      - EU2
      - EU3
      - IN1
      - CA1
      - AE1
      - UK1
      - AU1
      - KSA1

  QualysAccessToken:
    Type: String
    Description: 'Qualys Access Token (will be stored in Secrets Manager)'
    NoEcho: true

  QScannerLayerArn:
    Type: String
    Description: 'ARN of the Lambda Layer containing QScanner binary'

  EnableS3Results:
    Type: String
    Description: 'Create S3 bucket for storing scan results'
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableSNSNotifications:
    Type: String
    Description: 'Create SNS topic for scan notifications'
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  ScannerMemorySize:
    Type: Number
    Description: 'Memory size for Scanner Lambda (MB)'
    Default: 2048
    MinValue: 512
    MaxValue: 10240

  ScannerTimeout:
    Type: Number
    Description: 'Timeout for Scanner Lambda (seconds)'
    Default: 900
    MinValue: 60
    MaxValue: 900

  ScannerEphemeralStorage:
    Type: Number
    Description: 'Ephemeral storage for Scanner Lambda (MB)'
    Default: 2048
    MinValue: 512
    MaxValue: 10240

  EnableScanCache:
    Type: String
    Description: 'Enable DynamoDB scan cache to prevent duplicate scans'
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  CacheTTLDays:
    Type: Number
    Description: 'Number of days to cache scan results'
    Default: 30
    MinValue: 1
    MaxValue: 365

Conditions:
  CreateS3Bucket: !Equals [!Ref EnableS3Results, 'true']
  CreateSNSTopic: !Equals [!Ref EnableSNSNotifications, 'true']
  CreateScanCache: !Equals [!Ref EnableScanCache, 'true']

Resources:
  QualysCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}-qualys-credentials'
      Description: 'Qualys credentials for Lambda scanner'
      SecretString: !Sub |
        {
          "qualys_pod": "${QualysPod}",
          "qualys_access_token": "${QualysAccessToken}"
        }
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-qualys-credentials'
        - Key: ManagedBy
          Value: CloudFormation

  ScanResultsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-scan-results-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldScans
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-scan-results'
        - Key: ManagedBy
          Value: CloudFormation

  ScanNotificationsTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSNSTopic
    Properties:
      TopicName: !Sub '${AWS::StackName}-scan-notifications'
      DisplayName: 'Qualys Lambda Scan Notifications'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-scan-notifications'
        - Key: ManagedBy
          Value: CloudFormation

  ScanCacheTable:
    Type: AWS::DynamoDB::Table
    Condition: CreateScanCache
    Properties:
      TableName: !Sub '${AWS::StackName}-scan-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: function_arn
          AttributeType: S
      KeySchema:
        - AttributeName: function_arn
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-scan-cache'
        - Key: ManagedBy
          Value: CloudFormation

  ScannerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-scanner-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScannerLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ECRAccess
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeImages
                Resource: '*'
              - Sid: LambdaRead
                Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:GetFunctionConfiguration
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*'
              - Sid: SecretsManagerRead
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !GetAtt QualysCredentialsSecret.Id
              - !If
                - CreateScanCache
                - Sid: DynamoDBAccess
                  Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                  Resource: !GetAtt ScanCacheTable.Arn
                - !Ref AWS::NoValue
              - !If
                - CreateS3Bucket
                - Sid: S3Write
                  Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:PutObjectAcl
                  Resource: !Sub '${ScanResultsBucket.Arn}/*'
                - !Ref AWS::NoValue
              - !If
                - CreateSNSTopic
                - Sid: SNSPublish
                  Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: !Ref ScanNotificationsTopic
                - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-scanner-lambda-role'
        - Key: ManagedBy
          Value: CloudFormation

  ScannerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-scanner'
      RetentionInDays: 30

  # Package Lambda function code into S3
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-lambda-code-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  ScannerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-scanner'
      Description: 'Scans Lambda functions using Qualys QScanner (native runtime)'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ScannerLambdaRole.Arn
      MemorySize: !Ref ScannerMemorySize
      Timeout: !Ref ScannerTimeout
      EphemeralStorage:
        Size: !Ref ScannerEphemeralStorage
      Layers:
        - !Ref QScannerLayerArn
      Environment:
        Variables:
          QUALYS_SECRET_ARN: !Ref QualysCredentialsSecret
          RESULTS_S3_BUCKET: !If [CreateS3Bucket, !Ref ScanResultsBucket, '']
          SNS_TOPIC_ARN: !If [CreateSNSTopic, !Ref ScanNotificationsTopic, '']
          SCAN_CACHE_TABLE: !If [CreateScanCache, !Ref ScanCacheTable, '']
          SCAN_TIMEOUT: '300'
          CACHE_TTL_DAYS: !Ref CacheTTLDays
          QSCANNER_PATH: '/opt/bin/qscanner'
      Code:
        ZipFile: |
          # Placeholder - replace with actual code via S3 or inline
          # See scanner-lambda/lambda_function.py for full implementation
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Placeholder"}
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-scanner'
        - Key: ManagedBy
          Value: CloudFormation

  LambdaCreateEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-lambda-create'
      Description: 'Trigger scanner when Lambda function is created'
      State: ENABLED
      EventPattern:
        source:
          - aws.lambda
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - lambda.amazonaws.com
          eventName:
            - CreateFunction20150331
      Targets:
        - Arn: !GetAtt ScannerLambdaFunction.Arn
          Id: ScannerLambdaTarget

  LambdaUpdateCodeEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-lambda-update-code'
      Description: 'Trigger scanner when Lambda function code is updated'
      State: ENABLED
      EventPattern:
        source:
          - aws.lambda
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - lambda.amazonaws.com
          eventName:
            - UpdateFunctionCode20150331v2
      Targets:
        - Arn: !GetAtt ScannerLambdaFunction.Arn
          Id: ScannerLambdaTarget

  LambdaUpdateConfigEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-lambda-update-config'
      Description: 'Trigger scanner when Lambda function configuration is updated'
      State: ENABLED
      EventPattern:
        source:
          - aws.lambda
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - lambda.amazonaws.com
          eventName:
            - UpdateFunctionConfiguration20150331v2
      Targets:
        - Arn: !GetAtt ScannerLambdaFunction.Arn
          Id: ScannerLambdaTarget

  LambdaCreateEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScannerLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaCreateEventRule.Arn

  LambdaUpdateCodeEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScannerLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaUpdateCodeEventRule.Arn

  LambdaUpdateConfigEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScannerLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaUpdateConfigEventRule.Arn

  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/cloudtrail/${AWS::StackName}'
      RetentionInDays: 7

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-cloudtrail-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 7

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailBucket.Arn
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${CloudTrailBucket.Arn}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: CloudTrailBucketPolicy
    Properties:
      TrailName: !Sub '${AWS::StackName}-trail'
      S3BucketName: !Ref CloudTrailBucket
      IsLogging: true
      IsMultiRegionTrail: false
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailLogsRole.Arn
      EventSelectors:
        - ReadWriteType: WriteOnly
          IncludeManagementEvents: true
          DataResources: []

  CloudTrailLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudTrailLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt CloudTrailLogGroup.Arn

Outputs:
  ScannerLambdaArn:
    Description: 'ARN of the Scanner Lambda function'
    Value: !GetAtt ScannerLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ScannerLambdaArn'

  QualysSecretArn:
    Description: 'ARN of the Qualys credentials secret'
    Value: !Ref QualysCredentialsSecret
    Export:
      Name: !Sub '${AWS::StackName}-QualysSecretArn'

  ScanResultsBucketName:
    Description: 'Name of the S3 bucket for scan results'
    Condition: CreateS3Bucket
    Value: !Ref ScanResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ScanResultsBucket'

  ScanNotificationsTopicArn:
    Description: 'ARN of the SNS topic for scan notifications'
    Condition: CreateSNSTopic
    Value: !Ref ScanNotificationsTopic
    Export:
      Name: !Sub '${AWS::StackName}-ScanNotificationsTopic'

  CloudTrailName:
    Description: 'Name of the CloudTrail trail'
    Value: !Ref CloudTrail
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrail'

  ScanCacheTableName:
    Description: 'Name of the DynamoDB scan cache table'
    Condition: CreateScanCache
    Value: !Ref ScanCacheTable
    Export:
      Name: !Sub '${AWS::StackName}-ScanCacheTable'
